
name: mmtwfs

dependencies:
  - python>=3
  - astropy
  - sphinx
  - numpy
  - cython
  - matplotlib
  - scipy
  - scikit-image
  - pandas
  - ipython
  - jupyter
  - dnspython
  - docutils
  - pip:
    - photutils
    - ccdproc
    - astroscrappy
    - lmfit
    - "git+https://github.com/sphinx-gallery/sphinx-gallery.git"
    - sphinx-astropy
    - poppy
