
name: mmtwfs

dependencies:
  - python>=3
  - docutils
  - pip:
    - Cython
    - matplotlib
    - scipy
    - astropy
    - photutils
    - scikit-image
    - jupyter
    - dnspython
    - poppy
    - lmfit
    - ccdproc
    - astroscrappy
    - sphinx-astropy
