
name: mmtwfs

dependencies:
  - python>=3
  - Cython
  - docutils
  - astropy
  - matplotlib
  - scipy
  - scikit-image
  - jupyter
  - dnspython
  - pip:
    - photutils
    - poppy
    - lmfit
    - ccdproc
    - astroscrappy
    - sphinx-astropy
