jobs:

# Simple build to make sure egg_info works.
- job: LinuxEggInfo
  displayName: Testing egg_info
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  - script: python setup.py egg_info
    displayName: Running egg_info

# Now try with all optional dependencies. We also include the --readonly
# flag to make sure no files are being written to the temporary install
# location during testing.
- template: azure-template.yml
  parameters:
    os: linux
    name: LinuxAllDependencies
    displayName: Linux with all dependencies
    pip_args: .[test,all]
    runCodeCov: 'true'
    command: test --coverage

# Documentation build
- template: azure-template.yml
  parameters:
    os: linux
    name: LinuxDocumentation
    displayName: Documentation build
    pip_args: .[docs,all]
    command: build_docs
