name: Publish Release to PyPI

on:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    # NOTE: Uncomment "if" if you do not want this to run for every PR.
    # if: ((github.event_name == 'push' && startsWith(github.ref, 'refs/tags')) || contains(github.event.pull_request.labels.*.name, 'Build wheels'))
    secrets:
      pypi_token: ${{ secrets.PYPI_API_TOKEN }}
